services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
      POSTGRES_DB: ${POSTGRES_DB:-production_db}
    ports:
      - "5433:5432"
    volumes:
      - ./.data:/var/lib/postgresql/data
    networks:
      - pgvector-network

networks:
  pgvector-network:
    driver: bridge